# NUMPY 
### NumPy provides efficient storage.
### It is fast
### It is easy to learn
### It uses relatively less memory to store data.

In [77]:
import numpy as np  

In [78]:
print("hello world")

hello world


In [79]:
myarr = np.array([[3,6,32,7],[5,10,15,20]], np.int64)

In [80]:
myarr[1]

array([ 5, 10, 15, 20], dtype=int64)

In [81]:
myarr.shape

(2, 4)

In [82]:
myarr.dtype

dtype('int64')

In [83]:
myarr[0,1]=90

In [84]:
myarr

array([[ 3, 90, 32,  7],
       [ 5, 10, 15, 20]], dtype=int64)

# Array Creation methods

There are 6 general mechanisms for creating arrays:

Conversion from other Python structures (i.e. lists and tuples)

Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

Replicating, joining, or mutating existing arrays

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random)

## 1) Converting Python sequences to NumPy Arrays

In [85]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [86]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [87]:
np.array({10,20,30})

array({10, 20, 30}, dtype=object)

## 2) Intrinsic NumPy array creation functions

In [88]:
zeros = np.zeros((2,5))

In [89]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
rnge = np.arange(20)

In [91]:
rnge 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
#(first element, last element, how many numbers)
lspace = np.linspace(1,5,4)


In [93]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [94]:
#empty array of (4,6) with random numbers 
emp = np.empty((4,6))

In [95]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.33511562e-306, 7.56587585e-307, 7.56593017e-307],
       [1.24610383e-306, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22522597e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 9.34609790e-307,
        1.33511562e-306, 1.42417629e-306, 7.56605240e-307]])

In [96]:
#copy the size of old array and create new empty array of that size
emp_like= np.empty_like(lspace)

In [97]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [98]:
#identity matrix
ide = np.identity(45)

In [99]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [100]:
ide.shape

(45, 45)

In [101]:
arr = np.arange(80)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [103]:
#reshaping the old arr.... (multiplication of x,y should be equal to size of previous arr. (2,40) = 80)
arr = arr.reshape(2,40) 

In [104]:
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79]])

In [105]:
#converting into 1d array
arr=arr.ravel()

In [106]:
arr.shape

(80,)

In [107]:
#NUMPY AXIS
x= [[1,2,3],[4,5,6],[7,1,0]]

In [108]:
ar=np.array(x)

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [110]:
#axis0 = sum of values in each column 
#axis1 = sum of values in each row
ar.sum(axis=0)

array([12,  8,  9])

In [111]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [112]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [113]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [114]:
ar.flat

In [115]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [116]:
#no of dimensions 
ar.ndim

2

In [117]:
#no of elements in the array
ar.size

9

In [118]:
#total bytes consumed
ar.nbytes

36

In [119]:
one = np.array([15,5,8,12])

In [120]:
#give index of maximum value
one.argmax()

0

In [121]:
#return index of minimum value
one.argmin()

1

In [122]:
#indexes or sorted array
one.argsort()

array([1, 2, 3, 0], dtype=int64)

In [123]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [124]:
ar.argmin()

8

In [125]:
#return the indexes of max element at every row
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [126]:
#return the indexes of max element at every column
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [127]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [128]:
#will return the index of correct position of the element in the particular axis.
#in third row, 7 should be at index 2, 1 should be at index 1, 0 should be at index 0
#by deafult,sort along last axis (across)
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [129]:
#axis=0, sort along first axis(down)
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [130]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [131]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [132]:
ar2= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [133]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  9,  9]])

In [134]:
#in python, if we use + it will append the list
[1, 2] + [3,4]

[1, 2, 3, 4]

In [135]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  8,  0]])

In [136]:
#it will take sqrt element wise
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [137]:
ar.sum()

29

In [138]:
ar.max()

7

In [139]:
ar.min()

0

In [140]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [141]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [142]:
np.count_nonzero(ar)

8